### ISSUE TITLE
[Question]:  Object detection / inference model 

### ISSUE THREAD

**Issue by Cilouche** [SciSharp/TensorFlow.NET#1050]
### Description

Hello, 

Please, may I find an example of object detection / inference model with tensorflow and opencvSharp for images

Thanks

**Comment by AsakusaRinne** [comment]
Hi, examples are available here: https://github.com/SciSharp/SciSharp-Stack-Examples/tree/master/src%2FTensorFlowNET.Examples%2FObjectDetection

The examples use SharpCV. If you want to use opencv sharp it may need 1-2 weeks. Opencv Adapter is under development, which allows you to use opencv sharp with tf.net. You can also use it now by compiling it yourself: https://github.com/SciSharp/OpencvAdapter

**Comment by Cilouche** [comment]
Hi,

Thank you for your feedback, concerning the first example, I have an error on the model input
![image](https://user-images.githubusercontent.com/48053323/235863347-b74646b1-4b80-49ce-a673-04f657684622.png)

and when i cast
`var image_tensors = tf.cast(tn, tf.float32);`

another error persists 
![image](https://user-images.githubusercontent.com/48053323/235863665-2c39ee42-1e82-4fac-b110-c5c1d67a8ee8.png)

Thanks

**Comment by AsakusaRinne** [comment]
This is an example from tf.net before 0.7.0 (align with tf v1). You can try to checkout the example repo to branch "tf-align-v1". If the problem still appears, @Oceania2018 is more familiar with it. Or I'll give you a further feed back the day aftet tomorrow since I'm on vacation now and is not convenient for me to debug it. :)

**Comment by Oceania2018** [comment]
The data type doesn't match.
