### ISSUE TITLE
Unsafe code can't catch exception from native library

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/TensorFlow.NET#677]
@sharwell 
Is the unsafe function cause the exception won't be threw out to .NET?
https://github.com/SciSharp/TensorFlow.NET/blob/0ff31a35ec13229c712b79765ca19edca34d9754/src/TensorFlowNET.Core/Eager/c_api.eager.cs#L139

The original unit test is https://github.com/SciSharp/TensorFlow.NET/blob/0ff31a35ec13229c712b79765ca19edca34d9754/test/TensorFlowNET.UnitTest/Basics/VariableTest.cs#L87

When I ran it in `TensorFlowNET.Console` project to debug (it's easy to show console log than in UnitTest project).

![image](https://user-images.githubusercontent.com/1705364/102040057-37c2d600-3d91-11eb-80cc-b12be5b3c1cb.png)

BTW, when will `.net` support `SafeHandle[]` in the `DllImport`?

**Comment by sharwell** [comment]
The `unsafe` keyword doesn't make a difference here, but various other implementation details can. Can you add more details about the error you saw?

**Comment by Oceania2018** [comment]
No more error, just crash. That's the problem.

**Comment by sharwell** [comment]
The crash is caused by native code calling `abort()`, which terminates the process without giving a chance for exception handlers to run. I'm not able to provide more specific details because the debugger currently isn't able to locate the symbol file tensorflow.pdb. Do you know what symbol server it's hosted on?

**Comment by Oceania2018** [comment]
I don't have `pdb`, that's where the source code throw the error: https://github.com/tensorflow/tensorflow/blob/f3c5b4ea29b1bd536bd70fc332cc1ccdf1b09695/tensorflow/core/framework/tensor.cc#L659

**Comment by sharwell** [comment]
This `CHECK_EQ` failure is going through `LogMessageFatal`, which terminates the process and cannot be caught in managed code:

https://github.com/tensorflow/tensorflow/blob/0947a774d0edb41b6dd9f25bc8db6598c4f9c44a/tensorflow/tools/android/test/jni/object_tracking/logging.cc#L120

There are two ways to catch this error in managed code:

1. Alter the managed code to detect this condition in advance, and throw an exception before calling `TFE_Execute`
2. Alter the native code implementation to avoid calling `abort()` on this path

Having the PDB would make this process much easier when errors like this occur, since there may be a reasonable location to insert a status check in the `TFE_Execute` implementation that returns an error rather than terminating the process.
