### ISSUE TITLE
System.EntryPointNotFoundException:“无法在 DLL“tensorflow”中找到名为“TF_StringEncodedSize”的入口点。”

### ISSUE THREAD

**Issue by dreamsfly900** [SciSharp/TensorFlow.NET#773]
TF Core:
C-API 的字符串张量的字节布局已被更新，已与 TF Core/C++ 匹配，即 tensorflow::tstring/TF_TString 的连续数组。
C-API 函数 TF_StringDecode、TF_StringEncode 和 TF_StringEncodedSize 不再被使用，现已移除；关于 C 语言中的字符串访问/修改，请参见core/platform/ctstring.h。
tensorflow.python、tensorflow.core和tensorflow.compiler 模块现在被隐藏。这些模块不再是 TensorFlow 可访问 API 的一部分。
tf.raw_ops.Max 和 tf.raw_ops.Min 不再接受类型为tf.complex64 或 tf.complex128 的输入，因为这些操作对于复杂类型的行为没有被明确定义。
由于使用了 TensorFloat-32，某些 float32 操作在基于 Ampere 架构的 GPU 上以较低的精度运行，包括乘法和卷积。具体来说，这类运算的输入从 23 位精度四舍五入到 10 位。这对于深度学习模型来说，在实践中不太会造成问题。但在某些情况下，TensorFloat-32 （单精度浮点数值）也被用于 complex64 操作。
可以通过调用config.experimental.enable_tensor_float_32_execution(False) 来禁用 TensorFloat-32 。
默认情况下，XLA:CPU 和 XLA:GPU 设备不再注册。如果你真的需要它们，请使用 TF_XLA_FLAGS=--tf_xla_enable_xla_devices，但该标志位也将在后续版本中删除。
————————————————
版权声明：本文为CSDN博主「TensorFlow 社区」的原创文章，遵循CC 4.0 BY-SA版权协议，转载请附上原文出处链接及本声明。
原文链接：https://blog.csdn.net/tensorflowforum/article/details/111032130

**Comment by Andy-Elizabeth-mouse** [comment]
TF Core:
The byte layout of the C-API string tensor has been updated to match TF Core/C++, that is, a continuous array of tensorflow::tstring/TF_TString.
The C-API functions TF_StringDecode, TF_StringEncode and TF_StringEncodedSize are no longer used and have been removed; for string access/modification in C language, please refer to core/platform/ctstring.h.
The tensorflow.python, tensorflow.core and tensorflow.compiler modules are now hidden. These modules are no longer part of the TensorFlow accessible API.
tf.raw_ops.Max and tf.raw_ops.Min no longer accept input of type tf.complex64 or tf.complex128 because these operations are not clearly defined for the behavior of complex types.
Due to the use of TensorFloat-32, certain float32 operations run with lower precision on GPUs based on the Ampere architecture, including multiplication and convolution. Specifically, the input of this type of operation is rounded from 23 digits to 10 digits. This is unlikely to cause problems for deep learning models in practice. But in some cases, TensorFloat-32 (single-precision floating-point value) is also used for complex64 operations.
TensorFloat-32 can be disabled by calling config.experimental.enable_tensor_float_32_execution(False).
By default, XLA:CPU and XLA:GPU devices are no longer registered. If you really need them, please use TF_XLA_FLAGS=--tf_xla_enable_xla_devices, but this flag bit will also be removed in subsequent versions.
————————————————
Copyright statement: This article is the original article of the CSDN blogger "TensorFlow Community". It follows the CC 4.0 BY-SA copyright agreement. Please attach the original source link and this statement for reprinting.
Original link: https://blog.csdn.net/tensorflowforum/article/details/111032130
--Google Translate

**Comment by Oceania2018** [comment]
It's been already supported since [v2.5.0](https://www.nuget.org/packages/SciSharp.TensorFlow.Redist/2.5.0).
