### ISSUE TITLE
c_api.TF_OperationGetAttrMetadata

### ISSUE THREAD

**Issue by Oceania2018** [SciSharp/TensorFlow.NET#86]
Returns metadata about the value of the attribute `attr_name` of `oper`.
`TF_CAPI_EXPORT extern TF_AttrMetadata TF_OperationGetAttrMetadata(
    TF_Operation* oper, const char* attr_name, TF_Status* status);`

**Comment by Esther2013** [comment]
When I run the `CApiColocationTest.ColocateWith`, exception occurred. I'm trying to fix it, but have no idea about that exception.
![image](https://user-images.githubusercontent.com/33488376/50720396-3b606500-1072-11e9-8d3a-f2656e3fcf5f.png)

**Comment by Oceania2018** [comment]
@dotChris90 Could you help take a look?

**Comment by dotChris90** [comment]
@Oceania2018 @Esther2013 I am not 100% sure because the error can be have many reason. 

usual (according to error) it means you pass C# variables into C API (so dll or so) and the GC notice "oh the API try to change my varibales!! dont do this you bad guy!!!!).  ;) 
so the GC is try to protect variables from changes.

Most C APIs use pointer and so! sure the internal data behind this pointer are changed (ok so in other words most C APIs change data …. ). But usual this is just required for structs and not objects.

some solutions would be

1 ) we can try to add "ref" keyword to the PInvoke methods. reference is an identifier to the GC to allow change data. (this is done in the NetLib LAPACK providers - The LAPACK functions always work with pointers so the C# methods have arrays and ref based structure parameters). 

2 ) we could declare an unsafe method and work directly with pointer (dirty .... not my favourite).

3 ) we could try to use IntPtr objects at places for Pointer and later cast them to true objects.


**4 ) we could try to find an other function without a return value (do void). I am not 100% sure why but I noticed that PInvoke has sometimes problems with function which have a return value. In LAPACK I noticed it and this was the reason why i ususal take functions which have void output. But I do not have an explaining why this happens. **

**Comment by Oceania2018** [comment]
@dotChris90 Thanks for your info. I think I've tried every combination, still doesn't work. I just hold it. Next weeks I'll work on the Linear Regression.

**Comment by dotChris90** [comment]
just read the code

```CSHARP
 public static extern IntPtr TF_OperationGetAttrMetadata(IntPtr oper, string attr_name, IntPtr status);
```

From the C API header file i see we have a const char * as 2nd parameter. One thing we can try out is - map this 2nd parameter not to str but to a char[] array.

**Comment by Oceania2018** [comment]
I use string in the other functions they are all work. I can try in char[].

**Comment by dotChris90** [comment]
and remember - strings are the worst thing to cast from C++ to C# >.< 

some more options can be. 

to DLLImport add CharSet = CharSet.Ansi) --> [DLLImport("myDLL",CharSet = CharSet.Ansi)]

or 
```CSHARP
public static extern IntPtr TF_OperationGetAttrMetadata(IntPtr oper, [MarshalAs(UnmanagedType.LPStr)] string attr_name, IntPtr status);
```

**Comment by dotChris90** [comment]
Yes - but strings in general are extreeeeemeeeeee dynamic. 

CharSet - is it CharSet.Ansi or sth else? and what is the CallingConvention ? its so fuc..... annoyingful -.-

**Comment by fdncred** [comment]
What test can I reproduce this exception in?

**Comment by Oceania2018** [comment]
@fdncred Any luck for it?

**Comment by fdncred** [comment]
@Oceania2018 No. Still getting 'Attempted to read or write protected memory'. Typically with scenarios like this I have to step into the C++ code to understand what's going on because that dotnet error is not helpful. However, I'm not really sure I want to compile TF.

Have you looked at Miguel's code?
https://github.com/migueldeicaza/TensorFlowSharp

**Comment by Oceania2018** [comment]
Yes, I'm looking into it. Debugging...

**Comment by Oceania2018** [comment]
@fdncred I figured out:
![image](https://user-images.githubusercontent.com/1705364/50915337-326aed00-13fe-11e9-9616-3237d667b856.png)

`unsigned char` should be defined as `byte` in .net.

![image](https://user-images.githubusercontent.com/1705364/50915353-3ac32800-13fe-11e9-9cb9-77f54e2ac604.png)

@dotChris90

**Comment by fdncred** [comment]
Whoop Whoop!  Good job.

**Comment by dotChris90** [comment]
damn interesting.

but yes. since const the inner api can not change it. so GC will not complain.
